[workspace]
members = [
    "wit-host-codegen",
    "wit-guest-codegen",
    "example-project/host",
    "example-project/guest",
]

[workspace.package]
authors = ["Mason Ginter <mason@dagint.com>"]
edition = "2021"

[workspace.dependencies]
wit-parser = "0.6"