[package]
name = "wit-bindgen-build-script"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-rust = "0.4"
wit-bindgen-core = "0.4"