[package]
name = "wit-guest-codegen"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-rust = "0.4"
wit-parser = "0.6"